import type { Metadata } from "next";
import "./globals.css";
import Base from "../components/base";

export const metadata: Metadata = {
    title: "Next.js Admin Panel",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                {/* All UI routing through the Base component */}
                <Base>{children}</Base>
            </body>
        </html>
    );
}
